// ═══════════════════════════════════════════════════════════
//  CineVerse — Mock Movie Data
// ═══════════════════════════════════════════════════════════

const MOVIES = [
  {
    id: "1",
    title: "Inception",
    description: "A thief who steals corporate secrets through the use of dream-sharing technology is given the inverse task of planting an idea into the mind of a C.E.O. A visually stunning, mind-bending thriller that challenges the boundaries of reality.",
    releaseDate: "2010-07-16",
    contentRating: "PG-13",
    runtimeMinutes: 148,
    averageRating: 8.8,
    reviewCount: 2847,
    posterUrl: "https://image.tmdb.org/t/p/w500/9gk7adHYeDvHkCSEqAvQNLV5Uge.jpg",
    backdropUrl: "https://image.tmdb.org/t/p/w1280/s3TBrRGB1iav7gFOCNx3H31MoES.jpg",
    trailerUrl: "https://www.youtube.com/watch?v=YoHD9XEInc0",
    genres: ["Action", "Sci-Fi", "Thriller"],
    directors: [{ name: "Christopher Nolan" }],
    cast: ["Leonardo DiCaprio", "Joseph Gordon-Levitt", "Ellen Page", "Tom Hardy", "Ken Watanabe"]
  },
  {
    id: "2",
    title: "Interstellar",
    description: "A team of explorers travel through a wormhole in space in an attempt to ensure humanity's survival. A breathtaking sci-fi epic exploring love, time, and the cosmos.",
    releaseDate: "2014-11-07",
    contentRating: "PG-13",
    runtimeMinutes: 169,
    averageRating: 8.6,
    reviewCount: 2341,
    posterUrl: "https://image.tmdb.org/t/p/w500/gEU2QniE6E77NI6lCU6MxlNBvIx.jpg",
    backdropUrl: "https://image.tmdb.org/t/p/w1280/rAiYTfKGqDCRIIqo664sY9XZIvQ.jpg",
    trailerUrl: "https://www.youtube.com/watch?v=zSWdZVtXT7E",
    genres: ["Sci-Fi", "Drama"],
    directors: [{ name: "Christopher Nolan" }],
    cast: ["Matthew McConaughey", "Anne Hathaway", "Jessica Chastain", "Michael Caine"]
  },
  {
    id: "3",
    title: "The Dark Knight",
    description: "When the menace known as the Joker wreaks havoc and chaos on the people of Gotham, Batman must accept one of the greatest psychological and physical tests of his ability to fight injustice.",
    releaseDate: "2008-07-18",
    contentRating: "PG-13",
    runtimeMinutes: 152,
    averageRating: 9.0,
    reviewCount: 4120,
    posterUrl: "https://image.tmdb.org/t/p/w500/qJ2tW6WMUDux911r6m7haRef0WH.jpg",
    backdropUrl: "https://image.tmdb.org/t/p/w1280/or06FN3Dka5tukK1e9sl16pB3iy.jpg",
    trailerUrl: "https://www.youtube.com/watch?v=EXeTwQWrcwY",
    genres: ["Action", "Thriller", "Drama"],
    directors: [{ name: "Christopher Nolan" }],
    cast: ["Christian Bale", "Heath Ledger", "Aaron Eckhart", "Maggie Gyllenhaal", "Gary Oldman"]
  },
  {
    id: "4",
    title: "Pulp Fiction",
    description: "The lives of two mob hitmen, a boxer, a gangster and his wife, and a pair of diner bandits intertwine in four tales of violence and redemption.",
    releaseDate: "1994-10-14",
    contentRating: "R",
    runtimeMinutes: 154,
    averageRating: 8.9,
    reviewCount: 3456,
    posterUrl: "https://image.tmdb.org/t/p/w500/d5iIlFn5s0ImszYzBPb8JPIfbXD.jpg",
    backdropUrl: "https://image.tmdb.org/t/p/w1280/suaEOtk1N1sgg2MTM7oZd2cfVp3.jpg",
    genres: ["Crime", "Drama", "Thriller"],
    directors: [{ name: "Quentin Tarantino" }],
    cast: ["John Travolta", "Uma Thurman", "Samuel L. Jackson", "Bruce Willis"]
  },
  {
    id: "5",
    title: "The Shawshank Redemption",
    description: "Two imprisoned men bond over a number of years, finding solace and eventual redemption through acts of common decency. A timeless masterpiece of hope and friendship.",
    releaseDate: "1994-09-23",
    contentRating: "R",
    runtimeMinutes: 142,
    averageRating: 9.3,
    reviewCount: 5678,
    posterUrl: "https://image.tmdb.org/t/p/w500/q6y0Go1tsGEsmtFryDOJo3dEmqu.jpg",
    backdropUrl: "https://image.tmdb.org/t/p/w1280/kXfqcdQKsToO0OUXHcrrNCHDBzO.jpg",
    genres: ["Drama"],
    directors: [{ name: "Frank Darabont" }],
    cast: ["Tim Robbins", "Morgan Freeman", "Bob Gunton", "William Sadler"]
  },
  {
    id: "6",
    title: "Parasite",
    description: "Greed and class discrimination threaten the newly formed symbiotic relationship between the wealthy Park family and the destitute Kim clan.",
    releaseDate: "2019-05-30",
    contentRating: "R",
    runtimeMinutes: 132,
    averageRating: 8.5,
    reviewCount: 1987,
    posterUrl: "https://image.tmdb.org/t/p/w500/7IiTTgloJzvGI1TAYymCfbfl3vT.jpg",
    backdropUrl: "https://image.tmdb.org/t/p/w1280/TU9NIjwzjoKPwQHoHshkFcQUCG.jpg",
    genres: ["Drama", "Thriller", "Comedy"],
    directors: [{ name: "Bong Joon-ho" }],
    cast: ["Song Kang-ho", "Lee Sun-kyun", "Cho Yeo-jeong", "Choi Woo-shik"]
  },
  {
    id: "7",
    title: "The Godfather",
    description: "The aging patriarch of an organized crime dynasty transfers control of his clandestine empire to his reluctant son.",
    releaseDate: "1972-03-24",
    contentRating: "R",
    runtimeMinutes: 175,
    averageRating: 9.2,
    reviewCount: 4899,
    posterUrl: "https://image.tmdb.org/t/p/w500/3bhkrj58Vtu7enYsLlegkAoz0K.jpg",
    backdropUrl: "https://image.tmdb.org/t/p/w1280/tmU7GeKVDCZrEVRl1KZlTxm6l2g.jpg",
    genres: ["Crime", "Drama"],
    directors: [{ name: "Francis Ford Coppola" }],
    cast: ["Marlon Brando", "Al Pacino", "James Caan", "Robert Duvall", "Diane Keaton"]
  },
  {
    id: "8",
    title: "Avengers: Endgame",
    description: "After the devastating events of Infinity War, the Avengers assemble once more to reverse Thanos' actions and restore balance to the universe.",
    releaseDate: "2019-04-26",
    contentRating: "PG-13",
    runtimeMinutes: 181,
    averageRating: 8.4,
    reviewCount: 6234,
    posterUrl: "https://image.tmdb.org/t/p/w500/or06FN3Dka5tukK1e9sl16pB3iy.jpg",
    backdropUrl: "https://image.tmdb.org/t/p/w1280/7RyHsO4yDXtBv1zUU3mTpHeQ0d5.jpg",
    genres: ["Action", "Sci-Fi"],
    directors: [{ name: "Anthony Russo" }, { name: "Joe Russo" }],
    cast: ["Robert Downey Jr.", "Chris Evans", "Mark Ruffalo", "Chris Hemsworth", "Scarlett Johansson"]
  },
  {
    id: "9",
    title: "Spirited Away",
    description: "During her family's move to the suburbs, a sullen 10-year-old girl wanders into a world ruled by gods, witches, and monsters.",
    releaseDate: "2003-03-28",
    contentRating: "PG",
    runtimeMinutes: 125,
    averageRating: 8.6,
    reviewCount: 2109,
    posterUrl: "https://image.tmdb.org/t/p/w500/39wmItIWsg5sZMyRUHLkWBcuVCM.jpg",
    backdropUrl: "https://image.tmdb.org/t/p/w1280/bSXfU4dwZyBA1vMmXvejdRXBvuF.jpg",
    genres: ["Animation", "Fantasy"],
    directors: [{ name: "Hayao Miyazaki" }],
    cast: ["Daveigh Chase", "Suzanne Pleshette", "Miyu Irino"]
  },
  {
    id: "10",
    title: "The Matrix",
    description: "A computer hacker learns from mysterious rebels about the true nature of his reality and his role in the war against its controllers.",
    releaseDate: "1999-03-31",
    contentRating: "R",
    runtimeMinutes: 136,
    averageRating: 8.7,
    reviewCount: 3201,
    posterUrl: "https://image.tmdb.org/t/p/w500/f89U3ADr1oiB1s9GkdPOEpXUk5H.jpg",
    backdropUrl: "https://image.tmdb.org/t/p/w1280/fNG7i7RqMErkcqhohV2a6cV1Ehy.jpg",
    genres: ["Action", "Sci-Fi"],
    directors: [{ name: "The Wachowskis" }],
    cast: ["Keanu Reeves", "Laurence Fishburne", "Carrie-Anne Moss", "Hugo Weaving"]
  },
  {
    id: "11",
    title: "Whiplash",
    description: "A promising young drummer enrolls at a cut-throat music conservatory where his dreams of greatness are mentored by an instructor who will stop at nothing to realize a student's potential.",
    releaseDate: "2014-10-10",
    contentRating: "R",
    runtimeMinutes: 107,
    averageRating: 8.5,
    reviewCount: 1876,
    posterUrl: "https://image.tmdb.org/t/p/w500/7fn624j5lj3xTme2SgiLCeuedmO.jpg",
    backdropUrl: "https://image.tmdb.org/t/p/w1280/fRGxZuo7jJUWQsVg9PREb98Aclp.jpg",
    genres: ["Drama", "Thriller"],
    directors: [{ name: "Damien Chazelle" }],
    cast: ["Miles Teller", "J.K. Simmons", "Melissa Benoist"]
  },
  {
    id: "12",
    title: "Get Out",
    description: "A young African-American visits his white girlfriend's parents for the weekend, where his simmering uneasiness about their reception of him eventually reaches a boiling point.",
    releaseDate: "2017-02-24",
    contentRating: "R",
    runtimeMinutes: 104,
    averageRating: 7.7,
    reviewCount: 1543,
    posterUrl: "https://image.tmdb.org/t/p/w500/tFXcEccSQMVl9dsvXCRdo2jKsoo.jpg",
    backdropUrl: "https://image.tmdb.org/t/p/w1280/mHIuKxTcY0qkO7igdqxGxPDuMjh.jpg",
    genres: ["Horror", "Thriller"],
    directors: [{ name: "Jordan Peele" }],
    cast: ["Daniel Kaluuya", "Allison Williams", "Bradley Whitford"]
  },
  {
    id: "13",
    title: "La La Land",
    description: "While navigating their careers in Los Angeles, a pianist and an actress fall in love while attempting to reconcile their aspirations for the future.",
    releaseDate: "2016-12-09",
    contentRating: "PG-13",
    runtimeMinutes: 128,
    averageRating: 8.0,
    reviewCount: 2233,
    posterUrl: "https://image.tmdb.org/t/p/w500/uDO8zWDhfWwoFdKS4fzkUJt0Rf0.jpg",
    backdropUrl: "https://image.tmdb.org/t/p/w1280/nadTlnTE8bCMnIYsb4Z9QxX4UBY.jpg",
    genres: ["Romance", "Drama"],
    directors: [{ name: "Damien Chazelle" }],
    cast: ["Ryan Gosling", "Emma Stone", "John Legend"]
  },
  {
    id: "14",
    title: "Joker",
    description: "In Gotham City, mentally troubled comedian Arthur Fleck is disregarded and mistreated by society. He then embarks on a downward spiral of revolution and bloody crime.",
    releaseDate: "2019-10-04",
    contentRating: "R",
    runtimeMinutes: 122,
    averageRating: 8.4,
    reviewCount: 2876,
    posterUrl: "https://image.tmdb.org/t/p/w500/udDclJoHjfjb8Ekgsd4FDteOkCU.jpg",
    backdropUrl: "https://image.tmdb.org/t/p/w1280/n6bUvigpRFqSwmPp1m2YADwSx5P.jpg",
    genres: ["Drama", "Thriller"],
    directors: [{ name: "Todd Phillips" }],
    cast: ["Joaquin Phoenix", "Robert De Niro", "Zazie Beetz"]
  },
  {
    id: "15",
    title: "Dune",
    description: "Feature adaptation of Frank Herbert's science fiction novel about the son of a noble family entrusted with the protection of the most valuable asset in the galaxy.",
    releaseDate: "2021-10-22",
    contentRating: "PG-13",
    runtimeMinutes: 155,
    averageRating: 8.0,
    reviewCount: 1654,
    posterUrl: "https://image.tmdb.org/t/p/w500/d5NXSklpcvkCgyg6rGS1iiXmCJe.jpg",
    backdropUrl: "https://image.tmdb.org/t/p/w1280/iopYFB1b6Bh7FWZh3onQhph1sih.jpg",
    genres: ["Sci-Fi", "Action"],
    directors: [{ name: "Denis Villeneuve" }],
    cast: ["Timothée Chalamet", "Zendaya", "Rebecca Ferguson", "Oscar Isaac"]
  },
  {
    id: "16",
    title: "Oppenheimer",
    description: "The story of J. Robert Oppenheimer's role in the development of the atomic bomb during World War II.",
    releaseDate: "2023-07-21",
    contentRating: "R",
    runtimeMinutes: 180,
    averageRating: 8.9,
    reviewCount: 3102,
    posterUrl: "https://image.tmdb.org/t/p/w500/8Gxv8gSFCU0XGDykEGv7zR1n2ua.jpg",
    backdropUrl: "https://image.tmdb.org/t/p/w1280/rLb2cwF3Pazuxaj0sRXQ037tGI1.jpg",
    genres: ["Drama", "Thriller"],
    directors: [{ name: "Christopher Nolan" }],
    cast: ["Cillian Murphy", "Emily Blunt", "Matt Damon", "Robert Downey Jr."]
  }
];

const REVIEWS = {
  "1": [
    { id: "r1", username: "cinephile99", displayName: "Alex M.", rating: 10, title: "A mind-bending masterpiece", content: "Nolan outdoes himself with this layered, intricate thriller that rewards repeated viewing. The concept of entering dreams is executed with stunning visual precision. I've seen it seven times and still notice new details.", tags: ["mind-bending", "rewatch"], spoiler: false, helpful: 142, date: "2024-01-15" },
    { id: "r2", username: "movielover", displayName: "Jamie K.", rating: 8, title: "Complex but rewarding", content: "Takes multiple viewings to fully grasp, but every frame has a purpose. Hans Zimmer's score is absolutely iconic. DiCaprio delivers a career-best performance balancing vulnerability and resolve.", tags: ["great-score", "great-acting"], spoiler: false, helpful: 89, date: "2024-01-20" },
    { id: "r3", username: "filmcritic_uk", displayName: "Sarah B.", rating: 9, title: "The best heist film ever made", content: "Forget Ocean's Eleven. This is the ultimate heist movie where the heist happens inside someone's mind. The rotating hallway fight scene alone is worth the ticket price.", tags: ["action", "innovative"], spoiler: false, helpful: 67, date: "2024-02-01" }
  ],
  "3": [
    { id: "r4", username: "batfan42", displayName: "Bruce W.", rating: 10, title: "Heath Ledger is beyond words", content: "This isn't a superhero movie. It's a crime epic that happens to feature Batman. Ledger's Joker is the greatest villain performance in cinema history.", tags: ["heath-ledger", "oscar-worthy"], spoiler: false, helpful: 234, date: "2024-01-10" }
  ],
  "5": [
    { id: "r5", username: "hopeful_heart", displayName: "Morgan F.", rating: 10, title: "The most hopeful film I've ever seen", content: "In a world that can feel dark and hopeless, Shawshank reminds us that the human spirit cannot be imprisoned. Morgan Freeman's narration is pure poetry.", tags: ["hopeful", "timeless"], spoiler: false, helpful: 312, date: "2024-01-05" }
  ]
};
